version: '3.5'

services:
  node-api:
    container_name: jobhub
    restart: always
    ports:
      - '${SERVER_PORT}:3000'
    image: jobhub
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=docker
    command: 'npm start'
    networks:
      - sp-network
  mongo-db:
    image: mongo
    container_name: jobhub-mongodb
    ports:
      - '${DATABASE_PORT}:27017-27019'
    networks:
      - sp-network
networks:
  sp-network:
    name: sp-network
    driver: bridge
